[package]
name = "dfmm-kit"
version = "0.0.1"
edition = "2021"
authors = ["Colin Roberts <colin@autoparallel.xyz>"]
description = "The Rust kit for the DFMM contracts."
license = "Apache-2.0"
keywords = ["ethereum", "smart-contracts", "automated market makers"]
readme = "../README.md"

[dependencies]
arbiter-core.workspace = true
arbiter-engine = "0.3.0"
arbiter-macros = "0.1.2"
arbiter-bindings = "0.1.6"

# Ethereum
ethers.workspace = true

# Async
tokio.workspace = true
async-trait = "0.1.77"
futures-util = "0.3.30"

# Serde 
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

# Errors and tracing
anyhow = "1.0.80"
tracing.workspace = true
tracing-subscriber.workspace = true

# CLI
clap = { version = "4.5.1", features = ["derive"] }

[[bin]]
name = "kit"
path = "main.rs"
